#!/usr/bin/env bash

set -e

if [ "${EUID}" != "0" ]; then
    exec sudo "${0}"
fi

set -x

if [ ! -d "/usr/share/plymouth/themes" ]; then
    echo "\"/usr/share/plymouth/themes\" directory does not exist" >&2
    exit 1
fi

cp -r "$(dirname "${0}")"/vortex-ubuntu /usr/share/plymouth/themes/
update-alternatives \
    --install \
    /usr/share/plymouth/themes/default.plymouth \
    default.plymouth \
    /usr/share/plymouth/themes/vortex-ubuntu/vortex-ubuntu.plymouth \
    100

update-alternatives \
    --set \
    default.plymouth \
    /usr/share/plymouth/themes/vortex-ubuntu/vortex-ubuntu.plymouth

update-initramfs -u
